/**
 * 期刊投稿助手组件
 * 提供投稿信生成、审稿回复建议、投稿流程跟踪等功能
 */

import React, { useState } from 'react'
import {
  Card,
  Steps,
  Button,
  Form,
  Input,
  Select,
  Typography,
  Space,
  Tag,
  List,
  Collapse,
  Alert,
  Tabs,
  Badge,
  message,
  Tooltip,
  Divider,
  Empty,
  Modal,
  Timeline,
  Progress
} from 'antd'
import {
  EditOutlined,
  SendOutlined,
  MessageOutlined,
  CheckCircleOutlined,
  FileTextOutlined,
  RobotOutlined,
  SaveOutlined,
  CopyOutlined,
  ReloadOutlined,
  EyeOutlined,
  CalendarOutlined,
  BellOutlined
} from '@ant-design/icons'
import { aiService } from '@/services/aiService'
import type { Journal } from '@/services/journalService'
import styles from './SubmissionAssistant.module.css'

const { Title, Text, Paragraph } = Typography
const { TextArea } = Input
const { Option } = Select
const { Panel } = Collapse
const { TabPane } = Tabs
const { Step } = Steps

// 投稿阶段
export type SubmissionStage =
  | 'prepare'
  | 'cover_letter'
  | 'submit'
  | 'under_review'
  | 'revision'
  | 'accepted'
  | 'rejected'

// 投稿任务
interface SubmissionTask {
  id: string
  title: string
  description: string
  completed: boolean
  required: boolean
  deadline?: string
}

// 审稿意见
interface ReviewComment {
  id: string
  reviewer: string
  type: 'major' | 'minor' | 'suggestion'
  content: string
  lineNumber?: number
  response?: string
  status: 'pending' | 'responded' | 'resolved'
}

interface SubmissionAssistantProps {
  journal: Journal
  paperTitle: string
  paperAbstract: string
  onComplete?: () => void
}

const SubmissionAssistant: React.FC<SubmissionAssistantProps> = ({
  journal,
  paperTitle,
  paperAbstract,
  onComplete
}) => {
  const [currentStage, setCurrentStage] = useState<SubmissionStage>('prepare')
  const [activeTab, setActiveTab] = useState('checklist')
  const [generating, setGenerating] = useState(false)
  const [coverLetter, setCoverLetter] = useState('')
  const [responseLetter, setResponseLetter] = useState('')
  const [selectedComments, setSelectedComments] = useState<string[]>([])
  const [tasks, setTasks] = useState<SubmissionTask[]>([
    { id: '1', title: '检查格式要求', description: '确保论文符合期刊格式规范', completed: false, required: true },
    { id: '2', title: '准备投稿信', description: '撰写吸引编辑的投稿信', completed: false, required: true },
    { id: '3', title: '推荐审稿人', description: '提供3-5位潜在审稿人名单', completed: false, required: false },
    { id: '4', title: '准备利益冲突声明', description: '声明与论文相关的利益冲突', completed: false, required: true },
    { id: '5', title: '检查引用格式', description: '确保引用格式符合期刊要求', completed: false, required: true },
    { id: '6', title: '上传补充材料', description: '准备图表、数据集等补充材料', completed: false, required: false },
  ])

  // 模拟审稿意见
  const [reviewComments] = useState<ReviewComment[]>([
    {
      id: '1',
      reviewer: 'Reviewer #1',
      type: 'major',
      content: '实验设计的对照组设置不够充分，建议增加更多的基线对比实验来验证方法的有效性。',
      status: 'pending'
    },
    {
      id: '2',
      reviewer: 'Reviewer #1',
      type: 'minor',
      content: '图3的x轴标签不够清晰，请修正。',
      status: 'pending'
    },
    {
      id: '3',
      reviewer: 'Reviewer #2',
      type: 'suggestion',
      content: '建议与最近发表的Smith et al. (2024)工作进行对比讨论。',
      status: 'pending'
    }
  ])

  // 生成投稿信
  const generateCoverLetter = async () => {
    setGenerating(true)
    try {
      // 模拟AI生成
      await new Promise(r => setTimeout(r, 2000))
      const generatedLetter = `Dear Editor-in-Chief,

We are submitting our manuscript entitled "${paperTitle}" for consideration for publication in ${journal.name}.

[This is a generated cover letter template. In the real implementation, this would be generated by the AI service based on the paper content and journal information.]

Thank you for your consideration.

Sincerely,
[Your Name]`
      setCoverLetter(generatedLetter)
      message.success('投稿信生成完成')
    } catch (error) {
      message.error('生成失败')
    } finally {
      setGenerating(false)
    }
  }

  // 生成回复信
  const generateResponseLetter = async () => {
    if (selectedComments.length === 0) {
      message.warning('请至少选择一条审稿意见')
      return
    }
    setGenerating(true)
    try {
      await new Promise(r => setTimeout(r, 2000))
      const generatedResponse = `Dear Editor and Reviewers,

Thank you for your thorough review and constructive feedback on our manuscript. We have carefully addressed all the comments and revised the manuscript accordingly. Below are our point-by-point responses:

[This is a generated response letter template. In the real implementation, this would be generated by the AI service.]

Best regards,
[Your Name]`
      setResponseLetter(generatedResponse)
      message.success('回复信生成完成')
    } catch (error) {
      message.error('生成失败')
    } finally {
      setGenerating(false)
    }
  }

  // 切换任务完成状态
  const toggleTask = (taskId: string) => {
    setTasks(prev => prev.map(t =>
      t.id === taskId ? { ...t, completed: !t.completed } : t
    ))
  }

  // 计算完成进度
  const progress = Math.round((tasks.filter(t => t.completed).length / tasks.length) * 100)

  // 渲染投稿清单
  const renderChecklist = () => (
    <div className={styles.checklist}>
      <Alert
        message="投稿准备进度"
        description={`已完成 ${tasks.filter(t => t.completed).length}/${tasks.length} 项任务`}
        type={progress === 100 ? 'success' : 'info'}
        showIcon
        action={<Progress percent={progress} size="small" style={{ width: 100 }} />}
      />
      <List
        className={styles.taskList}
        dataSource={tasks}
        renderItem={task => (
          <List.Item
            actions={[
              <Button
                type={task.completed ? 'primary' : 'default'}
                size="small"
                icon={task.completed ? <CheckCircleOutlined /> : undefined}
                onClick={() => toggleTask(task.id)}
              >
                {task.completed ? '已完成' : '标记完成'}
              </Button>
            ]}
          >
            <List.Item.Meta
              title={
                <Space>
                  <Text delete={task.completed}>{task.title}</Text>
                  {task.required && <Tag color="red">必需</Tag>}
                </Space>
              }
              description={task.description}
            />
          </List.Item>
        )}
      />
    </div>
  )

  // 渲染投稿信生成
  const renderCoverLetter = () => (
    <div className={styles.coverLetterSection}>
      <Space direction="vertical" style={{ width: '100%' }}>
        <Alert
          message="AI 投稿信生成"
          description="基于论文内容和期刊信息，自动生成专业的投稿信"
          type="info"
          showIcon
          action={
            <Button
              type="primary"
              icon={<RobotOutlined />}
              onClick={generateCoverLetter}
              loading={generating}
            >
              生成投稿信
            </Button>
          }
        />
        {coverLetter && (
          <Card
            title="投稿信预览"
            extra={
              <Space>
                <Button icon={<CopyOutlined />} onClick={() => {
                  navigator.clipboard.writeText(coverLetter)
                  message.success('已复制')
                }}>
                  复制
                </Button>
                <Button type="primary" icon={<SaveOutlined />}>
                  保存
                </Button>
              </Space>
            }
          >
            <TextArea
              value={coverLetter}
              onChange={e => setCoverLetter(e.target.value)}
              rows={15}
              className={styles.letterEditor}
            />
          </Card>
        )}
      </Space>
    </div>
  )

  // 渲染审稿回复
  const renderReviewResponse = () => (
    <div className={styles.reviewResponse}>
      <Alert
        message="审稿意见回复助手"
        description="选择审稿意见，AI将协助生成专业的回复"
        type="info"
        showIcon
      />
      <Divider />
      <Title level={5}>审稿意见列表</Title>
      <List
        dataSource={reviewComments}
        renderItem={comment => (
          <List.Item
            actions={[
              <Button
                type={selectedComments.includes(comment.id) ? 'primary' : 'default'}
                size="small"
                onClick={() => {
                  setSelectedComments(prev =>
                    prev.includes(comment.id)
                      ? prev.filter(id => id !== comment.id)
                      : [...prev, comment.id]
                  )
                }}
              >
                {selectedComments.includes(comment.id) ? '已选择' : '选择'}
              </Button>
            ]}
          >
            <List.Item.Meta
              title={
                <Space>
                  <Text strong>{comment.reviewer}</Text>
                  <Tag color={comment.type === 'major' ? 'red' : comment.type === 'minor' ? 'orange' : 'blue'}>
                    {comment.type === 'major' ? '主要问题' : comment.type === 'minor' ? '次要问题' : '建议'}
                  </Tag>
                </Space>
              }
              description={comment.content}
            />
          </List.Item>
        )}
      />
      {selectedComments.length > 0 && (
        <>
          <Divider />
          <Button
            type="primary"
            icon={<RobotOutlined />}
            onClick={generateResponseLetter}
            loading={generating}
            block
          >
            为选中的 {selectedComments.length} 条意见生成回复
          </Button>
        </>
      )}
      {responseLetter && (
        <Card
          title="回复信"
          className={styles.responseLetterCard}
          extra={
            <Button icon={<CopyOutlined />} onClick={() => {
              navigator.clipboard.writeText(responseLetter)
              message.success('已复制')
            }}>
              复制
            </Button>
          }
        >
          <TextArea
            value={responseLetter}
            onChange={e => setResponseLetter(e.target.value)}
            rows={10}
            className={styles.letterEditor}
          />
        </Card>
      )}
    </div>
  )

  // 渲染投稿流程
  const renderProcess = () => (
    <div className={styles.processGuide}>
      <Steps
        direction="vertical"
        current={['prepare', 'cover_letter', 'submit', 'under_review', 'revision', 'accepted'].indexOf(currentStage)}
        items={[
          { title: '准备阶段', description: '完成投稿前检查清单' },
          { title: '撰写投稿信', description: '生成并优化投稿信' },
          { title: '正式投稿', description: '通过期刊系统提交' },
          { title: '审稿中', description: '等待审稿意见' },
          { title: '修改回复', description: '根据意见修改并回复' },
          { title: '录用', description: '论文被正式接收' }
        ]}
      />
      <Divider />
      <Card title="投稿时间线">
        <Timeline
          items={[
            { children: '准备论文初稿', color: 'green' },
            { children: '选择目标期刊', color: 'green' },
            { children: '格式调整与检查', color: progress === 100 ? 'green' : 'blue' },
            { children: '撰写投稿信', color: coverLetter ? 'green' : 'gray' },
            { children: '正式投稿', color: 'gray' },
            { children: '等待审稿结果', color: 'gray' }
          ]}
        />
      </Card>
    </div>
  )

  return (
    <div className={styles.submissionAssistant}>
      <Card
        title={
          <Space>
            <SendOutlined />
            <span>期刊投稿助手 - {journal.name}</span>
          </Space>
        }
        className={styles.mainCard}
      >
        <Tabs
          activeKey={activeTab}
          onChange={setActiveTab}
          type="card"
          items={[
            {
              key: 'checklist',
              label: (
                <span>
                  <CheckCircleOutlined /> 投稿清单
                </span>
              ),
              children: renderChecklist()
            },
            {
              key: 'cover_letter',
              label: (
                <span>
                  <EditOutlined /> 投稿信
                </span>
              ),
              children: renderCoverLetter()
            },
            {
              key: 'review_response',
              label: (
                <span>
                  <MessageOutlined /> 审稿回复
                  <Badge count={reviewComments.length} style={{ marginLeft: 8 }} />
                </span>
              ),
              children: renderReviewResponse()
            },
            {
              key: 'process',
              label: (
                <span>
                  <CalendarOutlined /> 投稿流程
                </span>
              ),
              children: renderProcess()
            }
          ]}
        />
      </Card>
    </div>
  )
}

export default SubmissionAssistant
